[main] EOS-13871 changes commented for node replacement option from UI
Seagate/cortx-management-portal pull request #135
Opened 2020-10-05 05:48 UTC by namrata-khake-ui

# Front-end 

## Problem Statement
<pre>
  <code>
Story Ref (if any): EOS-13871
  </code>
</pre>
## Unit testing on RPM done
<pre>
  <code>
locally done
  </code>
</pre>
## Problem Description
<pre>
  <code>
Remove Node replacement Option of GUI
  </code>
</pre>
## Solution
<pre>
  <code>
- Commented code from UI and node API's
  </code>
</pre>
![image](https://user-images.githubusercontent.com/64768901/95044105-383d5180-06fc-11eb-9a45-266e6a7d60b9.png)

## Unit Test Cases
<pre>
  <code>
- Done locally
  </code>
</pre>

2020-10-05 06:12 UTC, shrimetta requested changes
Please comment in swagger config also

2020-10-05 06:40 UTC, namrata-khake-ui commented
> Please comment in swagger config also

I have checked both swagger files and I didn't find API changes
/api/v1/maintenance/cluster/replace_node_status

2020-10-05 06:48 UTC, shrimetta approved these changes

2020-10-06 06:29 UTC, kupranay approved these changes

2020-10-13 13:31 UTC, merged