Unable to list Nodes on system maintenance page on CSM GU if hostname…
Seagate/cortx-management-portal pull request #139
Opened 2020-10-05 09:23 UTC by JayshreeAmore

# UI

 CSM UI : Unable to list Nodes on system maintenance page on CSM GU if hostname is null
## Problem Statement
<pre>
  <code>
    Story Ref (if any):EOS-13929
  </code>
</pre>
## Unit testing on RPM done
<pre>
  <code>
  No
  </code>
</pre>
## Problem Description
<pre>
  <code>
  </code>
</pre>
## Solution/Screenshots

 
![image](https://user-images.githubusercontent.com/66409360/95062300-69c51580-071a-11eb-8e2f-954532d7a41a.png)

<pre>
  <code>
  </code>
</pre>
## Unit Test Cases
<pre>
  <code>
   1)tested  node replacement with dummy data 
  </code>
</pre>… is null

Signed-off-by: Jayshree More <jayshree.more@seagate.com>

2020-10-05 09:29 UTC, namrata-khake-ui approved these changes

2020-10-13 09:21 UTC, shrimetta requested changes

2020-10-14 08:09 UTC, JayshreeAmore commented on gui/src/components/maintenance/cortx-resource.vue
> +              e.hostname !== null
done

2020-10-14 08:09 UTC, JayshreeAmore commented on gui/src/components/maintenance/cortx-resource.vue
> +              e.hostname !== null
done

2020-10-14 08:10 UTC, JayshreeAmore commented on gui/src/components/maintenance/cortx-resource.vue
> +            e.hostname !== null
done

2020-10-14 09:51 UTC, shrimetta approved these changes

2020-10-16 12:35 UTC, kupranay approved these changes

2020-10-16 12:37 UTC, merged