[Cortx] UI Text review changes-EOS-14222
Seagate/cortx-management-portal pull request #170
Opened 2020-10-19 05:34 UTC by namrata-khake-ui

# UI

text review changes

## Problem Statement
<pre>
  <code>
    Story Ref (if any):EOS-14222
  </code>
</pre>
## Unit testing on RPM done
<pre>
  <code>
  No
  </code>
</pre>
## Problem Description
<pre>
  <code>
1. On every account creation and access key popup warning text should changed from
"Save this information, you will not see it again. Download as CSV and close" to
"Click Download and close to save this information in CSV format."
2. All the column which are having any action edit or delete for those header name should be "Action"
3. Remove extra colon from text "I agree to the following:: "
Firmware Update 
4. Remove <br> firmware update text

  </code>
</pre>
## Solution/Screenshots
![image](https://user-images.githubusercontent.com/64768901/96404784-5d03ef80-11f9-11eb-93fb-8ba08c51198b.png)
![image](https://user-images.githubusercontent.com/64768901/96405273-69be1e80-11cc-11eb-8420-fad262e270bb.png)
![image](https://user-images.githubusercontent.com/64768901/96405311-7d698500-11cc-11eb-8f77-d09e96c009d7.png)
![image](https://user-images.githubusercontent.com/64768901/96405325-85c1c000-11cc-11eb-8803-47367fd3e623.png)
![image](https://user-images.githubusercontent.com/64768901/96405353-9a05bd00-11cc-11eb-800b-b07f07bffef9.png)
![image](https://user-images.githubusercontent.com/64768901/96405373-a8ec6f80-11cc-11eb-887d-2f008509b9ae.png)

<pre>
  <code>
  </code>
</pre>
## Unit Test Cases
<pre>
  <code>
  tested on locally
  </code>

2020-10-19 06:20 UTC, JayshreeAmore approved these changes

2020-10-19 06:27 UTC, shrimetta commented on gui/src/locales/en.json
> +    "updateStorageEnclosureClick": " Click Start update once the bundle file is uploaded successfully.",
Please remove space before Click

2020-10-19 06:27 UTC, shrimetta requested changes
Minor typo fix

2020-10-19 06:38 UTC, namrata-khake-ui commented on gui/src/locales/en.json
> +    "updateStorageEnclosureClick": " Click Start update once the bundle file is uploaded successfully.",
fixed this review comment

2020-10-19 07:12 UTC, shrimetta approved these changes

2020-10-22 10:13 UTC, kupranay approved these changes

2020-10-22 10:13 UTC, merged