[Cortx1.0-dev] EOS-14605-Added error code description in swagger.json for User and onboarding API's
Seagate/cortx-management-portal pull request #202
Opened 2020-10-30 10:38 UTC by namrata-khake-ui

# Front-end 

## Problem Statement
<pre>
  <code>
Story Ref (if any): EOS-14605 Swagger UI update with error code description
  </code>
</pre>
## Unit testing on RPM done
<pre>
  <code>
 NOT Required
  </code>
</pre>
## Problem Description
<pre>
  <code>
   Swagger UI update with error code description
  </code>
</pre>
## Solution
<pre>
  <code>
Added error code description to following component
- About
- User
- System configuraton
- CSM User
- S3
- S3 Access Key
- IAM User Access Key
- S3 user Access key

- Added or removed description which are not going to applicable for any API

  </code>
</pre>

## Unit Test Cases
<pre>
  <code>
- NOT required
  </code>
</pre>

Signed-off-by: Namrata Khake <namrata.khake@seagate.com>

2020-10-30 12:04 UTC, giftedUI requested changes

2020-10-30 12:04 UTC, giftedUI commented on web/src/config/swagger.json
> +		},
remove empty spaces

2020-11-02 04:38 UTC, namrata-khake-ui commented on web/src/config/swagger.json
> +		},
removed

2020-11-02 04:46 UTC, JayshreeAmore approved these changes

2020-11-02 12:30 UTC, navalkp approved these changes

2020-11-02 12:57 UTC, giftedUI approved these changes

2020-11-26 05:14 UTC, closed without merging