Eos 18778:added hostname in alert details.
Seagate/cortx-management-portal pull request #313
Opened 2021-04-01 07:06 UTC by JayshreeAmore

CSM UI : add hostname  alert details
## Problem Statement
<pre>
  <code>
    Story Ref (if any):EOS-EOS-18778
  </code>
</pre>
## Unit testing on RPM done
<pre>
  <code>
  No
  </code>
</pre>
## Problem Description
<pre>
  <code>
hostname must be shown on alerts details instead of  node id
  </code>
</pre>
## Solution/Screenshots

 
![image](https://user-images.githubusercontent.com/66409360/113256147-6506a600-92e6-11eb-8b88-b767cd7308ea.png)
![image](https://user-images.githubusercontent.com/66409360/113256176-70f26800-92e6-11eb-9c6e-68648967dcf9.png)

<pre>
  <code>
  </code>
</pre>
## Unit Test Cases
<pre>
  <code>
   1)tested alerts new tab hostname shows on screen
    2) tested alerts details page hostname shown on screen
    3)node id remove from alert page and details page
  </code>
</pre>

2021-04-01 10:36 UTC, shrimetta approved these changes

2021-04-01 10:39 UTC, Vrishali-web-dev approved these changes

2021-04-05 06:00 UTC, kupranay requested changes

2021-04-05 06:25 UTC, JayshreeAmore commented on gui/src/components/alerts/alert-details.vue
> +          <label>&nbsp;| {{ $t("alerts.host_name") }} :{{ alert.hostname}}</label>
done

2021-04-05 06:25 UTC, JayshreeAmore commented on gui/src/components/alerts/alert-history-details.vue
> +          <label>&nbsp;| {{ $t("alerts.host_name") }} :{{ alert.hostname}}</label>
done

2021-04-05 06:31 UTC, soniyamoholkar approved these changes

2021-04-05 07:42 UTC, kupranay approved these changes

2021-04-05 07:43 UTC, merged