EOS-19474 - CSM Audit-Log: Audit log should be shown in tabular format
Seagate/cortx-management-portal pull request #341
Opened 2021-04-29 05:12 UTC by azam93

Signed-off-by: Mughala Azam <mughala.azam@seagate.com>

Implementation of Table is done of Audit Log. Now data are showing in table format.

2021-04-29 05:36 UTC, shrimetta commented on gui/src/components/maintenance/auditlog.vue
> +            <template v-slot:item="props">
you can use <template v-slot:item.timestamp="props"> to customize single column instead of whole row.

2021-04-29 05:36 UTC, shrimetta requested changes
Please fix the templating in the table

2021-05-03 03:15 UTC, kupranay commented
please resolve conflicting files

2021-05-03 03:52 UTC, shrimetta commented
The code has been merged in another PR. Hence this PR can be closed.

2021-05-03 04:04 UTC, closed without merging

2021-05-03 04:05 UTC, azam93 commented
The code has been merged in another PR.