Custom table component for audit logs - WIP
Seagate/cortx-management-portal pull request #352
Opened 2021-05-12 10:30 UTC by NareshGopal

Signed-off-by: Naresh Gopalakrishnan <naresh.gopalakrishnan@seagate.com>

2021-05-12 10:49 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-05-24 10:49 UTC, NareshGopal commented
What can be expected in this commit?
1. Table will be displayed properly 
2. Default pagination is used and it works
3. Search and filter components are displayed on top but is won't function

2021-05-24 13:02 UTC, kupranay requested changes

2021-05-24 13:02 UTC, kupranay commented on gui/src/components/widgets/cortx-table.vue
> +          <!-- <template v-slot:item.timestamp="props">
remove commented code

2021-05-24 13:02 UTC, kupranay commented on gui/src/components/widgets/cortx-table.vue
> +          <!-- <template #footer="{props}">
remove commented code

2021-05-24 13:29 UTC, kupranay requested changes

2021-05-24 13:29 UTC, kupranay commented on gui/src/components/maintenance/auditlog.vue
>        text: "Response Code",
{ 
{
{
text_id:"timestamp"
text: "Timestamp",
      value: "timestamp",
      sortable: true,
      type: "time",
     show:"true/false",
    
    },

in your auditlog component code
check id is present in en.json if yes then display that value if not fallback to "text" field

2021-05-26 07:28 UTC, kupranay requested changes

2021-05-26 07:28 UTC, kupranay commented on gui/src/components/maintenance/cortx-auditlog.vue
> +    debugger;
remove debugger

2021-05-26 07:28 UTC, kupranay commented on gui/src/components/widgets/cortx-table.vue
> +<style>
export it as a separate css file

2021-05-26 07:38 UTC, kupranay approved these changes

2021-05-26 07:38 UTC, kupranay commented on gui/src/components/widgets/cortx-table.vue
> +                   :items="['Remote IP', 'Path','Method', 'User Agent']"
items should be coming from calling component

2021-05-26 07:38 UTC, kupranay commented on gui/src/components/maintenance/cortx-auditlog.vue
> +          <CortxTable
name of CortxTable should be changed to cortx-v-data-dablt

2021-05-31 12:19 UTC, closed without merging