EOS-20349 : Unsupported features show/hide on UI
Seagate/cortx-management-portal pull request #369
Opened 2021-05-16 10:57 UTC by Vrishali-web-dev

# UI
<pre>
  <code> 
Hide unsupported features on UI.
 </code>
</pre>
## Problem Statement
<pre>
  <code>
Story Ref (if any): EOS-20349 UI: unsupported features support on UI.
  </code>
</pre>
## Unit testing on RPM done
<pre>
  <code>
No: Backend is not yet ready, hence tested this with mock data on the UI.
  </code>
</pre>
## Problem Description
<pre>
  <code>
- Based on list of features received from the API, show/hide components on UI.
  </code>
</pre>
## Solution/Screenshots
<pre>
  <code> 
- Added code to check the list of unsupported features and based on this components are show and hide on the UI.
- Created v-feature directive to check the support of feature on UI.
  </code>
</pre>
## Unit Test Cases
<pre>
  <code>
CSM Login:
- Login to CSM UI
- Verify Capacity component in hidden
  </code>
</pre>
Capacity feature is hidden on the UI:

![image](https://user-images.githubusercontent.com/71690421/118394582-27c26180-b663-11eb-9367-a8c603e529d5.png)

Signed-off-by: Vrishali Danave <vrishali.danave@seagate.com>

2021-05-16 13:51 UTC, kupranay requested changes

2021-05-16 13:51 UTC, kupranay commented on gui/src/services/api-register.ts
> +  unsupported_features: `/api/${version}/unsupportedfeatures`,
is this API implemented in BE?

2021-05-16 13:51 UTC, kupranay commented on web/src/services/user/routes.ts
> +    path: "/api/:version/unsupportedfeatures",
this API is not implemented in BE, this wil throw error

2021-05-16 13:51 UTC, kupranay commented on gui/src/components/dashboard/dashboard.vue
> +      <v-col v-feature="capacity"
capacity and all other features must be part of a constant file

2021-05-16 13:51 UTC, kupranay commented on gui/src/components/dashboard/dashboard.vue
> +      <v-col v-feature="capacity"
why only capacity. Where is the implementation of other Features?

2021-05-18 06:54 UTC, Vrishali-web-dev commented
Implementation is different than expectation, new PR will be raised for the same and hence closing this PR.

2021-05-18 06:54 UTC, closed without merging