EOS-20375 UI: Admin user should be able to reset password for other a…
Seagate/cortx-management-portal pull request #396
Opened 2021-06-18 16:51 UTC by azam93

…dmin users

Signed-off-by: Mughala Azam <mughala.azam@seagate.com>

# Frontend

# Problem Statement

- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_
- _Describe the problem this patch intends to solve._

## Design

- _For Bug describe the fix here._
- _For feature, post the link to the solution page._
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]:_

## Coding

- _Coding conventions are followed and code is consistent. Yes/No?_
- _Confirm All CODACY errors are resolved. Yes/No?_

## Testing

- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No?_
- _Confirm Testing was performed with installed RPM. Yes/No?_
- _Confirm all the ut/regression/smoke test has been performed [Y/N]_

## Checklist

- _PR is self-reviewed? Yes/No?_
- _GitHub Issue is updated_
- _Jira is updated_
  -  _Check if the description is clear and explained._ 
    -  _Check Acceptance Criterion is defined._
      -  _All the tests performed should be mentioned before Resolving a JIRA._
        -  _Verification needs to be done before marked as Closed/Verified_
        - _Any interface change Yes/No?_
        - _Change notified to other gatekeepers: Yes/No?_
        - _Code reviews done and addressed: Yes/No?_
        - _Codacy issues reviewed and addressed: Yes/No?_
        - _Deployment test : Done/Not?_
        - _UT/smoke test: Done/Not?_
        - _Jira number added to PR: Yes/No?_
        - _Github merge done using UI: Yes/No?_
        - _Side effects on other features - deployment/update/node-replacement_
        - _Changes to quick-start-guide/community impact_
        - _All dependent component code PR are raised or already merged Yes/No_
        - _All dependent code already merged in landing branch Yes/No_

2021-06-21 11:14 UTC, kupranay requested changes
please update this with correct template

2021-06-22 05:03 UTC, shrimetta commented on gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
> +    if (vueInstance.$hasAccessToCsm(userPermissions.users + userPermissions.delete)) {
You can directly return vueInstance.$hasAccessToCsm(userPermissions.users + userPermissions.delete)

2021-06-22 05:03 UTC, shrimetta commented on gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
> +    this.onEditBtnClick(data)
semicolon is missing

2021-06-22 05:06 UTC, shrimetta commented on gui/src/models/download.ts
> +export interface csmUserQueryParam {
Name of the interface should be PascalCase

2021-06-22 06:35 UTC, shrimetta commented on gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
> +  public editActionCondition(record: any) {
Please refactor this method.

2021-06-22 06:36 UTC, shrimetta commented on gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
> +  private isLoggedInUserMonitor() {
Can have one method instead of three. Please refactor.

2021-06-22 06:36 UTC, shrimetta requested changes
Please implement the review comments.

2021-06-23 06:49 UTC, kupranay commented
[12:16 PM] Pranay Kumar
    Alexander Voronov i can see on the above build
Admin user is getting create but the URL fired is 
/api/v2/preboarding/user
​[12:16 PM] Pranay Kumar
    is this expected?
​[12:16 PM] Pranay Kumar
    or should it be using the same URL which was being used for CSM user creation on normal page?
​[12:17 PM] Alexander Voronov
    no, this is not expected at all
​[12:18 PM] Alexander Voronov
    

or should it be using the same URL which was being used for CSM user creation on normal page?

yes
​[12:18 PM] Pranay Kumar
    please update swagger document with new expectation... if not done already
Mughala Azam please update it on GUI

2021-06-28 04:43 UTC, closed without merging

2021-06-28 04:43 UTC, azam93 commented
Current PR - https://github.com/Seagate/cortx-management-portal/pull/412