EOS-20569: Admin user should not able to fetch success response from GET request for in valid endpoint.
Seagate/cortx-management-portal pull request #448
Opened 2021-07-16 06:22 UTC by azam93

# Frontend

# Problem Statement

- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ Yes
- _Describe the problem this patch intends to solve._ EOS-20569: Admin user should not able to fetch success response from GET request for in valid endpoint

## Design

- _For Bug describe the fix here._
- _For feature, post the link to the solution page._
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]:_

## Coding

- _Coding conventions are followed and code is consistent. Yes/No?_
- _Confirm All CODACY errors are resolved. Yes/No?_

## Testing

- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No?_
- _Confirm Testing was performed with installed RPM. Yes/No?_
- _Confirm all the ut/regression/smoke test has been performed [Y/N]_

## Checklist

- _PR is self-reviewed? Yes/No?_
- _GitHub Issue is updated_
- _Jira is updated_
  -  _Check if the description is clear and explained._ 
    -  _Check Acceptance Criterion is defined._
      -  _All the tests performed should be mentioned before Resolving a JIRA._
        -  _Verification needs to be done before marked as Closed/Verified_
        - _Any interface change Yes/No?_
        - _Change notified to other gatekeepers: Yes/No?_
        - _Code reviews done and addressed: Yes/No?_
        - _Codacy issues reviewed and addressed: Yes/No?_
        - _Deployment test : Done/Not?_
        - _UT/smoke test: Done/Not?_
        - _Jira number added to PR: Yes/No?_
        - _Github merge done using UI: Yes/No?_
        - _Side effects on other features - deployment/update/node-replacement_
        - _Changes to quick-start-guide/community impact_
        - _All dependent component code PR are raised or already merged Yes/No_
        - _All dependent code already merged in landing branch Yes/No_

![Scenario 1](https://user-images.githubusercontent.com/81350254/125901706-21d57dc1-c8c5-4beb-9d09-27a9df09230a.PNG)

![Scenario 2](https://user-images.githubusercontent.com/81350254/125901716-347a9fd0-8089-43e7-9811-366e43120cf4.PNG)

2021-07-20 03:23 UTC, shrimetta commented on web/src/services/s3/routes.ts
> -  {
Please check if it is there in swagger document also and remove it from there also.

2021-07-20 03:24 UTC, shrimetta requested changes
Minor comment. Please address.

2021-08-02 05:44 UTC, shrimetta approved these changes

2021-08-02 05:48 UTC, kupranay approved these changes

2021-08-02 05:55 UTC, merged