Eos 22900 web setup interfaces
Seagate/cortx-management-portal pull request #479
Opened 2021-08-05 16:51 UTC by soniyamoholkar

# Frontend

# Problem Statement

- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_
- _Describe the problem this patch intends to solve._

## Design

- _For Bug describe the fix here._
- _For feature, post the link to the solution page._
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]:_

## Coding

- _Coding conventions are followed and code is consistent. Yes/No?_
- _Confirm All CODACY errors are resolved. Yes/No?_

## Testing

- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No?_
- _Confirm Testing was performed with installed RPM. Yes/No?_
- _Confirm all the ut/regression/smoke test has been performed [Y/N]_

## Checklist

- _PR is self-reviewed? Yes/No?_
- _GitHub Issue is updated_
- _Jira is updated_
  -  _Check if the description is clear and explained._ 
    -  _Check Acceptance Criterion is defined._
      -  _All the tests performed should be mentioned before Resolving a JIRA._
        -  _Verification needs to be done before marked as Closed/Verified_
        - _Any interface change Yes/No?_
        - _Change notified to other gatekeepers: Yes/No?_
        - _Code reviews done and addressed: Yes/No?_
        - _Codacy issues reviewed and addressed: Yes/No?_
        - _Deployment test : Done/Not?_
        - _UT/smoke test: Done/Not?_
        - _Jira number added to PR: Yes/No?_
        - _Github merge done using UI: Yes/No?_
        - _Side effects on other features - deployment/update/node-replacement_
        - _Changes to quick-start-guide/community impact_
        - _All dependent component code PR are raised or already merged Yes/No_
        - _All dependent code already merged in landing branch Yes/No_

2021-08-09 08:49 UTC, pawankumarsrivastava requested changes

2021-08-09 08:49 UTC, pawankumarsrivastava commented on web/conf/csm_web.py
> +        self._desc = message % (args)
Use fstring

2021-08-09 08:49 UTC, pawankumarsrivastava commented on web/conf/csm_web.py
> +        Log.init(service_name = "csm_web_setup", log_path = "/tmp",
use /tmp/csm/setup_logs/

2021-08-09 08:49 UTC, pawankumarsrivastava commented on web/conf/csm_web_setup.py
> +            f"cmd   post_install, prepare, config, init, reset, test, pre_upgrade, post_upgrade\n"
add cleanup

2021-08-09 08:49 UTC, pawankumarsrivastava commented on web/conf/csm_web_setup.py
> +        parser1 = parser.add_parser(cls.name, help='setup %s' % name)
parser1 --> sub_parser

2021-08-09 08:49 UTC, pawankumarsrivastava commented on web/conf/csm_web_setup.py
> +        print(":PASS")
use sys.stdout.write

2021-08-09 12:15 UTC, soniyamoholkar commented on web/conf/csm_web.py
> +        self._desc = message % (args)
Done. Please check.

2021-08-09 12:15 UTC, soniyamoholkar commented on web/conf/csm_web.py
> +        Log.init(service_name = "csm_web_setup", log_path = "/tmp",
Done. Please check.

2021-08-09 12:16 UTC, soniyamoholkar commented on web/conf/csm_web_setup.py
> +            f"cmd   post_install, prepare, config, init, reset, test, pre_upgrade, post_upgrade\n"
Done. Please check.

2021-08-09 12:16 UTC, soniyamoholkar commented on web/conf/csm_web_setup.py
> +        parser1 = parser.add_parser(cls.name, help='setup %s' % name)
Done. Please check.

2021-08-09 12:16 UTC, soniyamoholkar commented on web/conf/csm_web_setup.py
> +        print(":PASS")
Done. Please check.

2021-08-10 05:28 UTC, pawankumarsrivastava approved these changes

2021-08-10 05:30 UTC, udayan-y21 approved these changes

2021-08-10 05:41 UTC, kupranay approved these changes

2021-08-10 05:41 UTC, merged