EOS-26764: Modified the capacity widget and dashboard widget placements
Seagate/cortx-management-portal pull request #536
Opened 2021-12-10 10:37 UTC by NareshGopal

# Problem Statement
- Modify the capacity widget as mentioned in the design https://www.figma.com/file/ptVXVm0FpIIle1hZKeZqgq/LR-Theme-Redesign-Options?node-id=0%3A1

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [x] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2021-12-10 12:31 UTC, sujit-h-singh requested changes

2021-12-10 12:33 UTC, NareshGopal commented on gui/src/components/dashboard/cortx-dashboard-capacity-gauge.vue
> +            this.usedLegendClass += ` capacity-green`;
Okay, I'll replace it with "".

2021-12-10 12:50 UTC, NareshGopal commented on gui/src/components/dashboard/cortx-dashboard-capacity-gauge.vue
> +const i18n = require("./dashboard.json");
Import statement was throwing vetur typescript error in VS Code. So, to get rid of that error I replaced it with require statement.

2021-12-10 13:12 UTC, sujit-h-singh commented on gui/src/components/dashboard/cortx-dashboard-capacity-gauge.vue
> +const i18n = require("./dashboard.json");
I think you could all together remove because it is not in use.

2021-12-13 04:50 UTC, sujit-h-singh approved these changes

2021-12-14 06:51 UTC, merged