EOS: 27080,EOS: 27124 Advance search and Filter Component.
Seagate/cortx-management-portal pull request #572
Opened 2022-01-05 07:59 UTC by sujit-h-singh

# Problem Statement
- Currently we have a search option and a filter separately. the new advance search is designed to include both the options.
- This would enable us to specifically filter data in different formats.

# Design
-  Figma design - [advance search ](https://www.figma.com/file/HuYNdGvVazilCkD8mJO1qQ/LR-Alert-page-redesign-options?node-id=0%3A1)

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [x] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [x] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [x] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [x] Changes done to WIKI / Confluence page / Quick Start Guide

2022-01-05 08:06 UTC, sujit-h-singh commented
screenshot of implementation.

2022-01-07 07:03 UTC, NareshGopal requested changes

2022-01-11 11:29 UTC, sujit-h-singh commented on gui/src/components/widgets/cortx-advance-search/cortx-advance-search-config.model.ts
> +  type: string;
Done

2022-01-11 11:30 UTC, NareshGopal approved these changes

2022-01-11 12:21 UTC, ajaysrivas approved these changes

2022-01-11 13:02 UTC, ajaysrivas commented
The security check failure will get fixed in main branch.

2022-01-11 13:02 UTC, merged